# ~/.bash_profile: executed by bash(1) for login shells.

# Include all the stuff that a non-login shell gets
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

# Include all my lovely lovely aliases
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

# A fancy colorized prompt
export PS1="\[\e[01;32m\]\u@\h\[\e[0m\] \w → "
