# ~/.bashrc: executed by bash(1) for non-login shells.

# Stuff only for OS X
if [ $(uname) == "Darwin"  ]; then
    # Include the the brew bin and sbins
    if [ -d /usr/local/bin ]; then
        PATH=/usr/local/bin:"${PATH}"
    fi

    if [ -d /usr/local/sbin ]; then
        PATH=/usr/local/sbin:"${PATH}"
    fi

    # Rubygems bin
    if [ -d /usr/local/opt/ruby/bin ]; then
        PATH=/usr/local/opt/ruby/bin:"${PATH}"
    fi

    # Node.js bin
    if [ -d /usr/local/share/npm/bin ]; then
        PATH=/usr/local/share/npm/bin:"${PATH}"
    fi

    # To pull in freetype libs
    if [ -d /usr/X11/lib ]; then
        PATH=/usr/X11/lib:"${PATH}"
    fi

    # To pull in other X11 stuff
    if [ -d /usr/X11/bin ]; then
        PATH=/usr/X11/bin:"${PATH}"
    fi

    # Homebrew Stuff
    export HOMEBREW_PREFIX=/usr/local
    export HOMEBREW_BUILD_FROM_SOURCE=1

    # Homebrew Stuff
    export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

    # TextMate Stuff
    export TM_PERL=/usr/local/plenv/shims/perl
    export TM_PERLTIDY=/usr/local/plenv/shims/perltidy
    export TM_GIT=/usr/local/bin/git

    # Default editor should be textmate for things that need it.
    export EDITOR="/usr/local/bin/mate -w"

    # Docker / boot2docker stuff
    export DOCKER_HOST="tcp://"
fi

# plenv stuff
export PLENV_ROOT=/usr/local/plenv

# execute plenv shims
if which plenv > /dev/null; then eval "$(plenv init -)"; fi
