# ~/.bashrc: executed by bash(1) for non-login shells.

# Stuff only for OS X
if [ $(uname) == "Darwin"  ]; then
    # Include the the brew bin and sbins
    if [ -d /usr/local/bin ]; then
        PATH=/usr/local/bin:"${PATH}"
    fi

    if [ -d /usr/local/sbin ]; then
        PATH=/usr/local/sbin:"${PATH}"
    fi

    # Rubygems bin
    if [ -d /usr/local/opt/ruby/bin ]; then
        PATH=/usr/local/opt/ruby/bin:"${PATH}"
    fi

    # Node.js bin
    if [ -d /usr/local/share/npm/bin ]; then
        PATH=/usr/local/share/npm/bin:"${PATH}"
    fi

    # To pull in freetype libs
    if [ -d /usr/X11/lib ]; then
        PATH=/usr/X11/lib:"${PATH}"
    fi

    # Homebrew Stuff
    export HOMEBREW_PREFIX=/usr/local

    # TextMate Stuff
    export TM_PERL=/usr/local/plenv/versions/5.18.1/bin/perl

    # Default editor should be textmate for things that need it.
    export EDITOR="/usr/local/bin/mate -w"

    # plenv stuff
    export PLENV_ROOT=/usr/local/plenv

    # execute plenv shims
    if which plenv > /dev/null; then eval "$(plenv init -)"; fi
fi
