# ~/.bash_aliases: Only aliased for login shells

# Colorize ls output cross platform
if [ $(uname) == "Linux"  ]; then
    alias ls='ls -lah --color=auto'
elif [ $(uname) == "Darwin"  ]; then
    alias ls='ls -lahG'
fi

# Just to be on the safe side when using command line mysql
alias mysql="mysql --safe-updates --show-warnings"

# OS X Specific aliases
if [ $(uname) == "Darwin"  ]; then
    # Remove duplicates from "open with" contextual menu
    alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

    # Do all manner of updates
    # alias update="sudo softwareupdate -i -a; brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; cpan-outdated | xargs cpanm --sudo -n"
fi
