# ~/.bash_profile: executed by bash(1) for login shells.

# Include all the stuff that a non-login shell gets
if [ -f "$HOME/.bashrc" ]; then
    source "$HOME/.bashrc"
fi

# Include some useful functions
if [ -f "$HOME/.bash_functions" ]; then
    source "$HOME/.bash_functions"
fi

# Include all my lovely lovely aliases
if [ -f "$HOME/.bash_aliases" ]; then
    source "$HOME/.bash_aliases"
fi

# Include bash completion
if [ -f "$HOME/.bash_completion" ]; then
    source "$HOME/.bash_completion"
fi

# Set the history time format
export HISTTIMEFORMAT="%d/%m/%y - %H:%M:%S: "

# Set the history file to be in the dotfiles directory
export HISTFILE="$HOME/.dotfiles/config/bash_history"

# Give us much much more storage for history
export HISTFILESIZE="100000"

# But don't load it all into memory
export HISTSIZE="500"

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Bash 4 only: `**/qux` will enter `./foo/bar/baz/qux`
shopt -s autocd 2> /dev/null

# Bash 4 only: `echo **/*.txt`
shopt -s globstar 2> /dev/null

# Make multiple-line commands count as one
shopt -s cmdhist

# Append to the history file immediately after running the command
# This keeps the history file in time order for analytics
# But doesn't break up-arrow behaviour with commands run in other shell
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND";

# A fancy colorized prompt
# Can't use \w on OS X: https://github.com/mxcl/homebrew/issues/23470
export PS1='\[\e[01;32m\]\u@\h\[\e[0m\] ${PWD/#$HOME/~} → '
